### ISSUE TITLE
Inimigos não se movimentam

### ISSUE THREAD

**Issue by rodrigoAMF** [rodrigoAMF/Zario#3]
Após modificação do código para padrão MVC inimigos ficam parados executando apenas a animação(padrão) de andar

![image](https://user-images.githubusercontent.com/11891722/49589726-45972280-f951-11e8-9ffb-ce846aab6eeb.png)

* Verificar linha 20 do enemyHorizontalComponent
       ` rb.velocity = new Vector2(enemyController.getMovementSpeed(), rb.velocity.y);`

**Comment by rodrigoAMF7** [comment]
fixed #3

**Comment by rodrigoAMF** [comment]
73749dfcd215f3e360d3f1b28bc73ff87b916b1c fixed
